spring:
  application:
    name: user-local-test
claim_intake_service_name: claim-intake_dev
benefit_coding_service_name: service-name_dev
claim_service_name: claim-service_dev
npi_lookup_url: "https://npiregistry.cms.hhs.gov/api"