spring:
  application:
    name: user-local-test
claim_intake_service_name: claim-intake_Local_yes11
benefit_coding_service_name: service-name_local11
claim_service_name: claim-service_local11
npi_lookup_url: https://npiregistry.cms.hhs.gov/api11
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh