spring:
  application:
    name: user-local-test
benefit_coding_service_name: service-name_pcf2
claim_service_name: claim-service_pcf2
npi_lookup_url: https://npiregistry.cms.hhs.gov/api2
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'