spring:
  application:
    name: user-local-test
claim_intake_service_name: claim-intake_Local
benefit_coding_service_name: service-name_local
claim_service_name: claim-service_local
npi_lookup_url: "https://npiregistry.cms.hhs.gov/api"