spring:
  application:
    name: userRepository-consumer
      
---

spring:
  profiles: local
logging:
  file: logs/claimprocessing.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8096

---

spring:
  profiles: pcf
  cloud:
    services:
      registrationMethod: route
      