npi_lookup_url: "https://npiregistry.cms.hhs.gov/api"
spring:
  application:
    name: userRepository-producer
  profiles:
    active:
    - local
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: pcf
  cloud:
    services:
      registrationMethod: route
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net:3306/ad_172e5f618a59743
    username: b5a5a982397e56
    password: 0ad23374
    driverClassName: com.mysql.jdbc.Driver
claim_intake_service_name: claim-intakePCF
benefit_coding_service_name: test_aaa
claim_service_name: claim-serviceAAAAPCF

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: kunal123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  file: logs/claimprocessing.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/ 
claim_intake_service_name: claim-intakeLocal
benefit_coding_service_name: '{cipher}6500f64edf4d8c3eff47c4c92560db686ecfe5973731b7aeff1c1989c76886f4dfccd70ab664f1cdb9499c795bf70c9e'
claim_service_name: claim-serviceAAAALoc
server:
  port: 8181